### ISSUE TITLE
Guideline for bug reporting

### ISSUE THREAD

**Issue by cswclui** [cswclui/SimPsyber#1]
If you have encountered bugs in the game, please describe the bug (with screenshots) and the step to reproduce the bug.

- Check if it is a new bug (not a duplicate of other reported bugs)
- Try to reproduce the bug yourself and conduct follow up tests to isolate the problem (e.g. what steps will or will not trigger the problem)

**Comment by WZY-Young6** [comment]
![697a2513a2d9335b37fa34a91e7cce4](https://user-images.githubusercontent.com/63724069/152789438-a715acda-31ff-4530-99cc-728fd38605ca.png)
![3708b88946f8f7e3cd517d9d14e4c07](https://user-images.githubusercontent.com/63724069/152789449-1cfc59c0-fa49-4e20-ae06-8db5fad0a011.png)
I upload two screenshot to demonstrate that I have meet  one bug when playing the game. This bug occurs when the game pops up a pay window after a prompt window has already appeared. In the rest of the game, whatever window I clicked on, the window to pay employees appeared along with it.

**Comment by cswclui** [comment]
> ![697a2513a2d9335b37fa34a91e7cce4](https://user-images.githubusercontent.com/63724069/152789438-a715acda-31ff-4530-99cc-728fd38605ca.png) ![3708b88946f8f7e3cd517d9d14e4c07](https://user-images.githubusercontent.com/63724069/152789449-1cfc59c0-fa49-4e20-ae06-8db5fad0a011.png) I upload two screenshot to demonstrate that I have meet one bug when playing the game. This bug occurs when the game pops up a pay window after a prompt window has already appeared. In the rest of the game, whatever window I clicked on, the window to pay employees appeared along with it. My student ID is 21044729g.

What is step to reproduce the problem?

**Comment by WZY-Young6** [comment]
> 

The method to reproduce the problem is that when the game prompts the employee for the third time, there is already a window prompt in the game screen.

**Comment by hugo22565** [comment]
After losing or completing the game, the clock in the next game fails to work. It always got stuck at 00:00 (SUN) in week 1.
CHAN Man Hei (21014981G)
![Problem](https://user-images.githubusercontent.com/99017961/154062461-2df8b4c7-2803-4815-8ee6-41aee8dd14e1.jpg)
.

**Comment by cswclui** [comment]
> After losing or completing the game, the clock in the next game fails to work. It always got stuck at 00:00 (SUN) in week 1. CHAN Man Hei (21014981G) ![Problem](https://user-images.githubusercontent.com/99017961/154062461-2df8b4c7-2803-4815-8ee6-41aee8dd14e1.jpg) .

Thanks for reporting. This defect should have been fixed now.
Seems this issue is the duplicate of #2

**Comment by cswclui** [comment]
> > 
> 
> The method to reproduce the problem is that when the game shows the window prompt to pay employees for the third time, there is already a window prompt in the game screen.

We are not sure how to reproduce the issue. We have tried to deploy some fix to avoid this from happening.
