### ISSUE TITLE
Invalid feature lead time on weekly report

### ISSUE THREAD

**Issue by bertbhy** [cswclui/SimPsyber#3]
No feature was deployed during week 3. After the week, I received a weekly report shows feature lead time with invalid numbers.
BEI Ho Yuen Bert (19004521g)

![feature lead time](https://user-images.githubusercontent.com/28197000/154851263-cbb8161d-d70f-4498-8653-6ebc8f6736f8.png)

**Comment by cswclui** [comment]
Thanks for reporting. This defect should have been fixed now.
