### ISSUE TITLE
Always get C grade for Mean Time to Recover

### ISSUE THREAD

**Issue by mollyng113** [cswclui/SimPsyber#4]
Played the game for several times and got different value of "Mean Time to Recover" result but the grading is always "C".
NG CHUN HAN 19004507G

![6](https://user-images.githubusercontent.com/100084781/154851941-3fdf5ec2-42cb-475e-98f7-51ffa0a9a4bc.png)
![5](https://user-images.githubusercontent.com/100084781/154851950-8d6ea30e-6785-445c-ba87-3805f02541d0.png)
![8](https://user-images.githubusercontent.com/100084781/154851974-19bcde14-b887-4031-acf6-dc5124a4caaf.png)
![7](https://user-images.githubusercontent.com/100084781/154851979-8f0df0c2-9aeb-42a7-99bf-1a635bd4d425.png)

**Comment by cswclui** [comment]
Thanks for reporting. This defect should have been fixed now.
